name: Test application

on:
    pull_request:
    push:
        branches:
            - 'master'
            - '[0-9]+.x'
            - '[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.x'
            - 'symfony6-support'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-version }} ${{ matrix.dependencies}}'
        runs-on: ubuntu-20.04
        env:
            SYMFONY_PHPUNIT_VERSION: 8
            SYMFONY_DEPRECATIONS_HELPER: "/.*each.*/"
            SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php-version: '7.4'
                      dependencies: 'lowest'
                    - php-version: '7.4'
                      symfony-version: 4.4.*
                      test-installation: true
                    - php-version: '7.4'
                      symfony-version: 5.0.*
                      test-installation: true
                    - php-version: '8.0'
                      symfony-version: 5.1.*
                      test-installation: true
                    - php-version: '8.1'
                      symfony-version: 6.3.*
                      test-installation: true

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'

            - name: Install Symfony Flex
              run: composer global require --no-progress --no-scripts --no-plugins symfony/flex

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: --prefer-dist

            - name: Execute test cases
              run: make test

            - name: Test installation
              if: ${{ matrix.test-installation == true }}
              run: make test
